### ISSUE TITLE
Syntax highlight breaks sometimes within user-defined functions

### ISSUE THREAD

**Issue by haikuvend** [Makopo/sublime-text-lsl#19]
The syntax highlight breaks within user-defined functions when variables are listed on more than one line.

For example:

```
udf(string str_a, string str_b)
{
    llSay(PUBLIC_CHANNEL, str_a + ", " + str_b + "!");
}

default
{
    touch_start(integer num_detected)
    {
        udf("Hello", llDetectedName(0));
    }
}
```

highlights just fine, but:

```
udf(string str_a, // here linebreak!
      string str_b)
{
    llSay(PUBLIC_CHANNEL, str_a + ", " + str_b + "!");
}

default
{
    touch_start(integer num_detected)
    {
        udf("Hello", llDetectedName(0));
    }
}
```

does not. The builtin function, builtin constant as well as the strings within `udf` are not highlighted correctly, variable types within udf are though.

If you need a screenshot to make this more clear, let me know. Cheers!

**Comment by buildersbrewery** [comment]
Do you think this issue can be resolved using Build 3084 and above using [.sublime-syntax](http://www.sublimetext.com/docs/3/syntax.html) files?

**Comment by Makopo** [comment]
I don't know and I'm reluctant to use .sublime-syntax in this project since
* I mainly use SublimeText2 and rarely use beta SublimeText3
* In [this forum](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17952) the author remarked:

> The sublime-syntax is not set in stone, and may be changing over the next few builds.

**Comment by buildersbrewery** [comment]
Maybe [this comment on sublimehq/Packages#115](https://github.com/sublimehq/Packages/issues/115#issuecomment-169626548) might help? Haven't made some time to try it yet, though.

**Comment by Makopo** [comment]
I believe b6f7b13b has also fixed this issue. Can you confirm if it has been resolved? Thanks.

**Comment by buildersbrewery** [comment]
Looks good.

Maybe you could change [Lines 237-243](https://github.com/Makopo/sublime-text-lsl/blob/b6f7b13b18774694069e8211e20257e294202f0b/lsl.tmLanguage#L237-L243) to add `commentblock` and `commentline` to the already included `storage_type`?

**Comment by Makopo** [comment]
Can you try the latest release? Thanks.

**Comment by buildersbrewery** [comment]
Nice catch with events in makopo/sublime-text-lsl@f0b1b36, [v2.3.2](https://github.com/Makopo/sublime-text-lsl/releases/tag/2.3.2) works for me.

**Comment by Makopo** [comment]
Then closing this issue. Thank you for confirmation.
