### ISSUE TITLE
`do.sublime-snippet` doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [Makopo/sublime-text-lsl#33]
The snippet [sublime-text-lsl / snippets / commons / do.sublime-snippet](https://github.com/Makopo/sublime-text-lsl/blob/master/snippets/commons/do.sublime-snippet) doesn't have the desired effect. The problem is in line 4 where it says:

``` xml
<snippet>
<content><![CDATA[do$LSL_SPACE_OR_NEWLINE{
$0;
}$LSL_SPACE_OR_NEWLINEwhile (${1:condition});]]></content>
<tabTrigger>do</tabTrigger>
<scope>meta.function.body.lsl, meta.event.body.lsl, meta.function.body.ossl, meta.event.body.ossl</scope>
<description>flow control</description>
</snippet>
```

`$LSL_SPACE_OR_NEWLINEwhile` is being ignored because it's an unknown tag.

**Comment by buildersbrewery** [comment]
Hi Mako,

FYI `${LSL_SPACE_OR_NEWLINE}` works in `*.sublime-completions` files as well. You can merge the snippet files into one completions file.

**Comment by buildersbrewery** [comment]
However you'll need to set a default indent style when loading the LSL package, because setting it in the `__init__` of `ChangeStyleCommand` is too late.

Compare:

https://github.com/buildersbrewery/linden-scripting-language/tree/master/sublimetext/LSL
