### ISSUE TITLE
Build 3070

### ISSUE THREAD

**Issue by ghost** [Makopo/sublime-text-lsl#34]
Hi Mako,

[Build 3070](https://www.sublimetext.com/3dev) finally has tool tips. See [this thread](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583&sid=27e63cf72334018dad8f225f33e2ffe1) for instructions on how to use them.

Have a nice day!

**Comment by buildersbrewery** [comment]
Simplest tool tips example I could find:

* [tylerl0706/Doge-Sublime-Plugin](https://github.com/tylerl0706/Doge-Sublime-Plugin)

**Comment by buildersbrewery** [comment]
![lsl-tooltips](https://cloud.githubusercontent.com/assets/13032004/15403744/bd1b3420-1dfa-11e6-961c-00ea5849e413.png)

---

Got tooltips working with a prebuilt JSON database similar to the one in Intellitip (link above). Now working on pulling data from kwdb directly. Will let you know as soon as I got it.

**Comment by Makopo** [comment]
The feature proposed requires EventListner to be implemented, and it may introduce some all-time performance issue no matter whether users use the tooltip or not. I'm finding the way not to enable EventListener when the user don't want this feature, but seems to be difficult and the project will go complicated. I'm considering another plugin project which enables lsl tooltip to keep this project simple. Thanks.

**Comment by Makopo** [comment]
I created a new plugin project: [Makopo/sublime-text-tooltip-lsl](/Makopo/sublime-text-tooltip-lsl)

Currently barely works.

I intend it not to be related to this plugin. If you have any further comment about this feature, please open the issue on the new project. Thanks.
