### ISSUE TITLE
Sublime Text 4

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/sublime-text-lsl#40]
## Sublime Text 4xxx Builds are coming...

[![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord&style=flat-square)](https://discord.gg/D43Pecu)

#### Licenses

You can use the ST4xxx Dev Builds with a valid ST3 License.

The packages repo at [`sublimehq/Packages`](https://github.com/sublimehq/Packages) has split off an `st3` branch and now uses `master` for ST4xxx Builds.

#### Other random info that came up yesterday and today, semi-related

- [VWBPE](https://www.vwbpe.org) is happening soon
- 32bit binaries aren't supported on Catalina anymore (`mcpp` for the linter)
- One of the SublimeHQ devs made a tool called [`sbnf`](https://github.com/BenjaminSchaaf/sbnf), which might come in handy
- There is a binary for testing syntaxes against tests, see [sublimehq/Packages:`.github/workflows/ci.yml`@master](https://github.com/sublimehq/Packages/blob/master/.github/workflows/ci.yml).
    - Currently testing against Build 4073.
- haven't looked at LSL stuff in ages, will send you a PR after being abroad until next week if I come up with some major improvements for the syntax file.
- it might make sense to have a second syntax with only the word lists for tooltips with snippets

**Comment by buildersbrewery** [comment]
* the binary for testing syntax files doesn't support branching (yet)

**Comment by buildersbrewery** [comment]
### Sublime Text 4xxx Docs

<https://www.sublimetext.com/docs/index.html>

Just a heads up:

* <https://www.sublimetext.com/docs> still redirects to <https://www.sublimetext.com/docs/3/index.html>
* Clicking the `Docs` labeled button at the top of the new docs pages, goes back to <https://www.sublimetext.com/docs> ... which redircts to the ST3 Docs. You might want to keep the base page open and open links in new tabs until this is fixed.

**Comment by Makopo** [comment]
Thank you for letting me know. I acknowledged.
I will try to keep this plugin backward compatible with sublime v3.2.2 until Sublime v5 is released.
