### ISSUE TITLE
Syntax Highlighting Incorrect on Closing Brackets

### ISSUE THREAD

**Issue by CandiceJoy** [Makopo/sublime-text-lsl#42]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/8854890/204111775-ff465b45-73e1-4f4a-b6cc-1de6aab4bb41.png">

**Comment by CandiceJoy** [comment]
The script works and the BB highlighter shows it correctly.

**Comment by Makopo** [comment]
I found that Mariana parses `punctuation.DEFINITION` that way.
C++ syntax uses `punctuation.SECTION`, so I imitated it. efc8028

**Comment by Makopo** [comment]
fixed in version 2.7.1
